### ISSUE TITLE
use react router to create links to pages with information on each launch

### ISSUE THREAD

**Issue by Cerchie** [stepzen-dev/stepzen-spacex-graphql#8]
https://reactrouter.com/

This issue is to be addressed after #5 is resolved.

**Comment by gagandeepp** [comment]
Interested ,please assign this to me

**Comment by Cerchie** [comment]
This issue is still available for now :)

**Comment by gagandeepp** [comment]
Assign this to me

**Comment by Cerchie** [comment]
Hey @gagandeepp, although I appreciate your interest in many of our issues, we want to make space for a variety of contributors. We've assigned you #7

**Comment by rek990** [comment]
Hi @Cerchie, I hope you are doing well! 

Is this issue still up for grabs?

**Comment by Cerchie** [comment]
@rek990 it's yours!

**Comment by Cerchie** [comment]
@rek990 I thought it was, but looks like it was addressed here https://github.com/stepzen-dev/stepzen-spacex-graphql/pull/22-- please feel free to grab another, or create an issue to start work in one of the examples in our monorepo here if you like https://github.com/stepzen-dev/examples

**Comment by rek990** [comment]
@Cerchie no problem: I'll definitely take a look at some of the other repos!
